### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by zhangwen9229** [cybercongress/js-amino#16]
publish to npm?

**Comment by TanNgocDo** [comment]
Thanks for raising this issue, I will try to adding documentation + unit test and finish some feature. Until now, please feel free to include the code to your project :) Or if you're willing to contribute to this project, I'm very happy :)

**Comment by zhangwen9229** [comment]
I'll try it.    ^_^ ^_^ ^_^

**Comment by TanNgocDo** [comment]
@zhangwen9229 , could you please try it: https://www.npmjs.com/package/js-amino ?

**Comment by zhangwen9229** [comment]
@TanNgocDo Thank you for your hard work. I will try later.
