### ISSUE TITLE
Prepare 1.0.0 release of js-amino

### ISSUE THREAD

**Issue by litvintech** [cybercongress/js-amino#30]
- [x] Create issue templates (Bug report, Feature request, Add Issue to Gitcoin)
- [x] Create PR template
- [x] Describe features (AS-IS) in README
- [x] Describe known bugs (TO-FIX) in README
- [x] Describe planned features (TO-DO) in README
- [x] Transfer to cybercongress's npm
- [x] Add logo to README
- [x] Add badges to README (test's coverage, npm, issues, gitcoin, license, PR)
- [x] Write exampes for different cases (all build-in types, use cases for cosmos's chains)
- [x] Describe Pull Requesing flow in README (Add at CONTRIBUTING.md)
- [x] Add list of maintainers and contributors to README
- [x] Add Gitcoin program description to README
- [x] Add small into to amino and serialization (motivation, princiles, vs protobuf) with pics to README
- [x] Great auto changelog
- [x] Add contributing.md
- [x] Add code of conduct
- [x] Add docs folder
- [x] Add auto docs collector

**Comment by TanNgocDo** [comment]
Do you have Logo ? Cybercongress ?

**Comment by TanNgocDo** [comment]
@all-contributors please add  @Thunnini

**Comment by TanNgocDo** [comment]
@all-contributors bot

**Comment by TanNgocDo** [comment]
@all-contributors lease add @Thunnini for code

**Comment by TanNgocDo** [comment]
@all-contributors lease add @Thunnini for code

**Comment by TanNgocDo** [comment]
@all-contributors please add @TanNgocDo for code and maintenance
@all-contributors please add @philipstanislaus for  documentation
@all-contributors please add @SaveTheAles for project management
@all-contributors please add @litvintech for code
@all-contributors please add @cyberadmin for Documentation
@all-contributors please add @ethanfrey for Tests

**Comment by TanNgocDo** [comment]
@all-contributors please add @TanNgocDo for code and maintenance

**Comment by TanNgocDo** [comment]
@all-contributors please add @philipstanislaus for documentation

**Comment by TanNgocDo** [comment]
@all-contributors please add @SaveTheAles for project management

**Comment by TanNgocDo** [comment]
@all-contributors please add @litvintech for code

**Comment by TanNgocDo** [comment]
@all-contributors please add @cyberadmin for Documentation

**Comment by TanNgocDo** [comment]
@all-contributors please add @ethanfrey for Tests

**Comment by TanNgocDo** [comment]
Is it ok for closing this @SaveTheAles , @litvintech ?

**Comment by mastercyb** [comment]
@SaveTheAles Looks like its time to publish
