### ISSUE TITLE
Question: Cosmos SDK types library

### ISSUE THREAD

**Issue by faboweb** [cybercongress/js-amino#41]
Hey,
just a question. Do you know if there is already a library/repo that has all the Cosmos SDK (transaction) types for amino-js?

Thanks for the help.

**Comment by TanNgocDo** [comment]
Hi @faboweb . We have just get started with this repo: https://github.com/cybercongress/cosmos-js
We intent to replicated all TX of Comos-sdk in client sign(including signing transaction and commit with js-tendermint). Do you think the idea is ok ?

**Comment by faboweb** [comment]
Very good idea. Js-tendermint is nice, but is very big (things to consider). Let me know where I can help.
